FROM golang:alpine

RUN apk add --no-cache git
RUN go install github.com/swaggo/swag/cmd/swag@latest

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download && go mod verify

COPY . .

RUN swag init -g internal/server/server.go --parseInternal

RUN go build -v -o ./build/app ./cmd

CMD ["./build/app"]